# configs/knight.toml
[model]
n_embd = 256
n_head = 8
n_layer = 10
block_size = 120
dropout = 0.2
save_name = "knight"

[training]
batch_size = 64
learning_rate = 3e-4
max_iters = 70000
save_event_inter = 5000
monitor_event_inter = 50
loss_eval_iter = 5 
device = 'cuda'
train_test_split = 0.9

[data]
min_elo = 2100
n_rows = 16000000
dataset_name = "main_set" 
dataset_path = "/home/isaac/c-gpt/data/dataset.parquet"
san_string_path = "misc/san_strings/san_string.txt"

[evaluation]
eval_num_games = 3
eval_lvls = [1,5,10]
stockfish_path = "stockfish"

[save]
save_cloud = 1 

[cloud]
bucket_name = 'c-gpt-data'
