# configs/queen.toml
[model]
n_embd = 512
n_head = 12
n_layer = 12
block_size = 120
dropout = 0.2
save_name = "queen"

[training]
batch_size = 64
learning_rate = 3e-4
max_iters = 100000
save_event_inter = 5000
monitor_event_inter = 50
loss_eval_iter = 5 
device = 'cuda'
train_test_split = 0.9

[data]
dataset_name = "main_set" 

[evaluation]
eval_num_games = 3
eval_lvls = [1,5,10]
stockfish_path = "stockfish"

[save]
save_cloud = 1 

[cloud]
bucket_name = 'c-gpt-data'
